CREATE DATABASE ATIVIDADETRIGGER;

USE  ATIVIDADETRIGGER;

CREATE TABLE ALUNO (
IDMATRICULA INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR (30) ,
IDADE INT (2) ,
SALA VARCHAR (10)
);

CREATE TABLE BKP_ALUNO (
IDMATRICULA INT PRIMARY KEY AUTO_INCREMENT,
NOME VARCHAR (30) ,
IDADE INT (2) ,
SALA VARCHAR (10)
);

INSERT INTO ALUNO VALUES ('1', "MARCIO", '18', "SALA 2");
INSERT  INTO ALUNO (NOME, IDADE, SALA) VALUES ("FRANCISCO", '18', "SALA 2");
INSERT INTO ALUNO (NOME, IDADE, SALA) VALUES ("josué", '18', "sala 2");
INSERT INTO ALUNO (NOME, IDADE, SALA) VALUES ("lair", '16', "sala 3");
INSERT INTO ALUNO (NOME, IDADE, SALA) VALUES ("MÁRIO", '18', "SALA 3");

DELETE FROM ALUNO
WHERE IDADE = 16;

SELECT * FROM ALUNO;
SELECT * FROM BKP_ALUNO;
 
DELIMITER &

CREATE TRIGGER BKP_ALUNINHO
BEFORE DELETE ON ALUNO
FOR EACH ROW
BEGIN
 
      INSERT INTO BKP_ALUNO VALUES
        (NOT NULL,OLD,IDMATRICULA,OLD.NOME,OLD.IDADE,OLD.SALA);
        
END

&
